###服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8099/eureka/

###api网关服务端口号
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul

### 配置网关反向代理
zuul:
  routes:
    ### 定义转发服务规则
    api-a: ### 这个 api-a 命名是随意的
      ### 当客户端发送请求 127.0.0.1:80/api-member/ 开头时，网关会将请求转发到会员服务
      path: /api-member/**              #定义请求路径
      serviceId: app-itmayiedu-member   #会员服务名称.当服务是集群时，zuul网关默认整合ribbon，自动实现负载均衡轮训机制
    api-b:
      ### 当客户端发送请求 127.0.0.1:80/api-order/ 开头时，网关会将请求转发到订单服务
      path: /api-order/**
      serviceId: app-itmayiedu-order
