###服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/

###api网关服务端口号
server:
  port: 8081
###网关名称
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true #zuul默认是小写 切换为gateway默认是大写  做兼容处理 加上该配置...
      routes:
        - id: taotao-user
          # lb代表从注册中心获取服务, 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: lb://USER
          # 优先级 数字越小 优先级越靠前
          order: 10000
          # 重点！转发该路径！
          predicates:
            - Path=/api/user/**

        - id: search_route
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/search/**

