###服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/

###api网关服务端口号
server:
  port: 8081
###网关名称
spring:
  application:
    name: service-zuul
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用自动根据服务ID生成路由
          lower-case-service-id: true # 设置路由的路径为小写的服务ID
      routes:
        - id: taotao-auth
          uri: lb://taotao-auth
          predicates:
            - Path=/taotao-auth/**
          filters:
            - StripPrefix=1 # 移除前缀 taotao-auth
        - id: taotao-admin
          uri: lb://taotao-user
          predicates:
            - Path=/taotao-user/**
          filters:
            - StripPrefix=1
